import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Sparkles, User, ChevronDown, ChevronUp, Clock } from 'lucide-react';

const MessageItem = ({ message, thinkingData }) => {
  const [thinkingExpanded, setThinkingExpanded] = useState(true);

  const isUser = message.role === 'user';

  return (
    <div className={`message ${isUser ? 'user' : 'assistant'}`}>
      <div className="message-avatar">
        {isUser ? <User size={18} /> : <Sparkles size={18} />}
      </div>
      
      <div className="message-content">
        {/* Thinking Block for Assistant */}
        {!isUser && thinkingData && thinkingData.isThinking && thinkingExpanded && (
          <div className="thinking-block">
            <div 
              className="thinking-header"
              onClick={() => setThinkingExpanded(!thinkingExpanded)}
            >
              <div className="thinking-spinner"></div>
              <span className="thinking-title">Thinking Process</span>
              <Clock size={14} style={{ marginLeft: 'auto', marginRight: '8px' }} />
              <span className="thinking-time">{thinkingData.elapsed}s</span>
              {thinkingExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </div>
            
            <div className="thinking-content">
              {thinkingData.steps.map((step, index) => (
                <div key={index} style={{ marginBottom: '8px', opacity: 0.8 }}>
                  → {step}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Message Content */}
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            code({ node, inline, className, children, ...props }) {
              const match = /language-(\w+)/.exec(className || '');
              return !inline && match ? (
                <div className="code-block">
                  <div className="code-header">
                    <span className="code-language">{match[1]}</span>
                    <button 
                      className="copy-code-btn"
                      onClick={() => navigator.clipboard.writeText(String(children))}
                    >
                      Copy code
                    </button>
                  </div>
                  <pre className="code-content" {...props}>
                    <code>{String(children).replace(/\n$/, '')}</code>
                  </pre>
                </div>
              ) : (
                <code className={className} {...props}>
                  {children}
                </code>
              );
            },
            p: ({ children }) => <p style={{ marginBottom: '12px' }}>{children}</p>,
            ul: ({ children }) => <ul style={{ marginBottom: '12px', paddingLeft: '20px' }}>{children}</ul>,
            ol: ({ children }) => <ol style={{ marginBottom: '12px', paddingLeft: '20px' }}>{children}</ol>,
            li: ({ children }) => <li style={{ marginBottom: '4px' }}>{children}</li>,
            strong: ({ children }) => <strong style={{ fontWeight: 600 }}>{children}</strong>,
          }}
        >
          {message.content}
        </ReactMarkdown>

        {/* Model Info for Assistant */}
        {!isUser && message.model && (
          <div style={{ 
            marginTop: '12px', 
            paddingTop: '12px', 
            borderTop: '1px solid var(--border-subtle)',
            fontSize: '0.75rem',
            color: 'var(--text-tertiary)'
          }}>
            Generated by {message.model}
          </div>
        )}
      </div>
    </div>
  );
};

export default MessageItem;
